[workspace] 
members = [
    "lifetime_annotations",
    "declarative_macros",
    "iterators",
    "smart_pointers_and_interior_mutability",
    "channels",
    "sorting_algorithms",
    "strtok",
    "boks",
    "atomics",
    "eksempel",
    "patience",
    "call-me"
]